export const ENABLE_CREATE_POST = 'ENABLE_CREATE_POST';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const FAVORITE_POST_FAILURE = 'FAVORITE_POST_FAILURE';
export const FAVORITE_POST_SUCCESS = 'FAVORITE_POST_SUCCESS';
export const FAVORITE_POST = 'FAVORITE_POST';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';
export const COMMENT_POST = 'COMMENT_POST';

export const STORE_IMG = 'STORE_IMG';
